# Generated by Django 4.2.1 on 2023-06-13 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_tasks_projecttasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_on',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='last_update_on',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projecttasks',
            name='last_update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
