# Generated by Django 4.2.1 on 2023-06-13 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_project_created_on_project_last_update_on_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='last_update_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
