# Generated by Django 4.2.1 on 2023-09-16 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_project_created_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='created_by',
            new_name='owner',
        ),
    ]
