# Generated by Django 4.2.1 on 2023-09-30 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_project_assigned_alter_project_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='assigned',
            field=models.ManyToManyField(blank=True, related_name='assigned', to=settings.AUTH_USER_MODEL),
        ),
    ]
